pub mod conjugation {
    #[derive(Clone, Debug, PartialEq, Eq, Hash)]
    pub enum ConjugationForm {
        Garu,
        Conditional,
        ConditionalContraction1,
        ConditionalContraction2,
        AttributiveConjunction,
        SpecialAttributive,
        SpecialAttributive2,
        ImperativeE,
        ImperativeI,
        ImperativeRo,
        ImperativeYo,
        Basic,
        BasicSokuonbin,
        OldBasic,
        NegativeU,
        NegativeNu,
        NegativeReru,
        Negative,
        NegativeSpecial,
        ModernBasic,
        ContinuousGozai,
        ContinuousTa,
        ContinuousTe,
        ContinuousDe,
        ContinuousNi,
        Continuous,
        OnbinBasic,
        Undefined(String),
    }

    impl ConjugationForm {
        pub fn parse(features: &[&str]) -> ConjugationForm {
            match features[5] {
                "ガル接続" => ConjugationForm::Garu,
                "仮定形" => ConjugationForm::Conditional,
                "仮定縮約１" => ConjugationForm::ConditionalContraction1,
                "仮定縮約２" => ConjugationForm::ConditionalContraction2,
                "体言接続" => ConjugationForm::AttributiveConjunction,
                "体言接続特殊" => ConjugationForm::SpecialAttributive,
                "体言接続特殊２" => ConjugationForm::SpecialAttributive2,
                "命令ｅ" => ConjugationForm::ImperativeE,
                "命令ｉ" => ConjugationForm::ImperativeI,
                "命令ｒｏ" => ConjugationForm::ImperativeRo,
                "命令ｙｏ" => ConjugationForm::ImperativeYo,
                "基本形" => ConjugationForm::Basic,
                "基本形-促音便" => ConjugationForm::BasicSokuonbin,
                "文語基本形" => ConjugationForm::OldBasic,
                "未然ウ接続" => ConjugationForm::NegativeU,
                "未然ヌ接続" => ConjugationForm::NegativeNu,
                "未然レル接続" => ConjugationForm::NegativeReru,
                "未然形" => ConjugationForm::Negative,
                "未然特殊" => ConjugationForm::NegativeSpecial,
                "現代基本形" => ConjugationForm::ModernBasic,
                "連用ゴザイ接続" => ConjugationForm::ContinuousGozai,
                "連用タ接続" => ConjugationForm::ContinuousTa,
                "連用テ接続" => ConjugationForm::ContinuousTe,
                "連用デ接続" => ConjugationForm::ContinuousDe,
                "連用ニ接続" => ConjugationForm::ContinuousNi,
                "連用形" => ConjugationForm::Continuous,
                "音便基本形" => ConjugationForm::OnbinBasic,
                other => ConjugationForm::Undefined(other.into()),
            }
        }
    }

    define_enum! {
        pub enum Conjugation features[4] {
            "*" => None,
            "カ変・クル" => KahenKuru(ConjugationForm),
            "カ変・来ル" => KahenKuruKanji(ConjugationForm),
            "サ変・スル" => SahenSuru(ConjugationForm),
            "サ変・－スル" => SahenSuruConnected(ConjugationForm),
            "サ変・－ズル" => SahenZuruConnected(ConjugationForm),
            "一段" => Ichidan(ConjugationForm),
            "一段・病メル" => IchidanYameru(ConjugationForm),
            "五段・カ行イ音便" => GodanKaIonbin(ConjugationForm),
            "五段・カ行促音便" => GodanKaSokuonbin(ConjugationForm),
            "五段・カ行促音便ユク" => GodanKaSokuonbinYuku(ConjugationForm),
            "五段・ガ行" => GodanGa(ConjugationForm),
            "五段・サ行" => GodanSa(ConjugationForm),
            "五段・タ行" => GodanTa(ConjugationForm),
            "五段・ナ行" => GodanNa(ConjugationForm),
            "五段・バ行" => GodanBa(ConjugationForm),
            "五段・マ行" => GodanMa(ConjugationForm),
            "五段・ラ行" => GodanRa(ConjugationForm),
            "五段・ラ行アル" => GodanRaAru(ConjugationForm),
            "五段・ラ行特殊" => GodanRaSpecial(ConjugationForm),
            "五段・ワ行ウ音便" => GodanWaUonbin(ConjugationForm),
            "五段・ワ行促音便" => GodanWaSokuonbin(ConjugationForm),
            "四段・カ行" => YodanKa(ConjugationForm),
            "四段・ガ行" => YodanGa(ConjugationForm),
            "四段・サ行" => YodanSa(ConjugationForm),
            "四段・タ行" => YodanTa(ConjugationForm),
            "四段・バ行" => YodanBa(ConjugationForm),
            "四段・マ行" => YodanMa(ConjugationForm),
            "四段・ラ行" => YodanRa(ConjugationForm),
            "四段・ハ行" => YodanHa(ConjugationForm),
            "ラ変" => Rahen(ConjugationForm),
            "上二・ダ行" => KaminiDa(ConjugationForm),
            "上二・ハ行" => KaminiHa(ConjugationForm),
            "下二・ア行" => ShimoniA(ConjugationForm),
            "下二・カ行" => ShimoniKa(ConjugationForm),
            "下二・ガ行" => ShimoniGa(ConjugationForm),
            "下二・サ行" => ShimoniSa(ConjugationForm),
            "下二・ザ行" => ShimoniZa(ConjugationForm),
            "下二・タ行" => ShimoniTa(ConjugationForm),
            "下二・ダ行" => ShimoniDa(ConjugationForm),
            "下二・ナ行" => ShimoniNa(ConjugationForm),
            "下二・ハ行" => ShimoniHa(ConjugationForm),
            "下二・バ行" => ShimoniBa(ConjugationForm),
            "下二・マ行" => ShimoniMa(ConjugationForm),
            "下二・ヤ行" => ShimoniYa(ConjugationForm),
            "下二・ラ行" => ShimoniRa(ConjugationForm),
            "下二・ワ行" => ShimoniWa(ConjugationForm),
            "下二・得" => ShimoniU(ConjugationForm),
            "一段・クレル" => IchidanKureru(ConjugationForm),
            "一段・ル" => IchidanRu(ConjugationForm),
            "形容詞・アウオ段" => AdjectiveAUO(ConjugationForm),
            "形容詞・イ段" => AdjectiveI(ConjugationForm),
            "特殊・ナイ" => SpecialNai(ConjugationForm),
            "特殊・タイ" => SpecialTai(ConjugationForm),
            "特殊・タ" => SpecialTa(ConjugationForm),
            "特殊・ダ" => SpecialDa(ConjugationForm),
            "特殊・デス" => SpecialDesu(ConjugationForm),
            "特殊・ジャ" => SpecialJa(ConjugationForm),
            "特殊・マス" => SpecialMasu(ConjugationForm),
            "特殊・ヌ" => SpecialNu(ConjugationForm),
            "文語・ベシ" => OldBeshi(ConjugationForm),
            "文語・ゴトシ" => OldGotoshi(ConjugationForm),
            "文語・ナリ" => OldNari(ConjugationForm),
            "文語・マジ" => OldMaji(ConjugationForm),
            "文語・シム" => OldShimu(ConjugationForm),
            "文語・キ" => OldKi(ConjugationForm),
            "文語・ケリ" => OldKeri(ConjugationForm),
            "文語・リ" => OldRi(ConjugationForm),
            "文語・ル" => OldRu(ConjugationForm),
            "不変化型" => NoConjugation(ConjugationForm),
            "形容詞・イイ" => AdjectiveII(ConjugationForm),
            "特殊・ドス" => SpecialDosu(ConjugationForm),
            "一段・得ル" => IchidanEru(ConjugationForm),
            "特殊・ヤ" => SpecialYa(ConjugationForm),
        }
    }
}
pub use self::conjugation::Conjugation;
